'use strict';

import maskPhone from './modules/maskPhone';
import showPhone from './modules/showPhone';
import showMenu from './modules/showMenu';
import backToUp from './modules/backToUp';
import showPopupRepairTypes from './modules/showPopupRepairTypes';
import showPopupPrivacy from './modules/showPopupPrivacy';
import showPopupConsultation from './modules/showPopupConsultation';
import toggleSchemeListTabs from './modules/toggleSchemeListTabs';
import toggleAccordion from './modules/toggleAccordion';
import sendForm from './modules/sendForm';
import showFormulaItemPopup from './modules/showFormulaItemPopup';
import showProblemsItemPopup from './modules/showProblemsItemPopup';
import reviewsSlider from './modules/reviewsSlider';
import showPopupTransparency from './modules/showPopupTransparency';
import toggleRepairTypesTab from './modules/toggleRepairTypesTab';

maskPhone();
showPhone();
showMenu();
backToUp();
showPopupRepairTypes();
showPopupPrivacy();
showPopupConsultation();
toggleSchemeListTabs();
toggleAccordion();
sendForm();
showFormulaItemPopup();
showProblemsItemPopup();
reviewsSlider();
showPopupTransparency();
toggleRepairTypesTab();
